version: "2.19.1"
services:
  db:
    image: mysql
    ports:
      - "9000:9000"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_TCP_PORT: 9000
      MYSQL_DATABASE: boardApi
    restart: unless-stopped
  api:
    build: .
    image: tttapi
    ports:
      - "8080:8080"
    volumes:
      - ./cont_logs:/app/logs
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://db:9000/boardApi?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
        "spring.datasource.password": "123456"
      }'
    restart: on-failure
    depends_on:
      - db
  ui:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./src/main/resources/static:/usr/share/nginx/html
    depends_on:
      - api
    restart: unless-stopped